declare module "@video-chat/ui" {
  export const Accordion: any
  export const AccordionContent: any
  export const AccordionItem: any
  export const AccordionTrigger: any
  export const Alert: any
  export const AlertDescription: any
  export const AlertDialog: any
  export const AlertDialogAction: any
  export const AlertDialogCancel: any
  export const AlertDialogContent: any
  export const AlertDialogDescription: any
  export const AlertDialogFooter: any
  export const AlertDialogHeader: any
  export const AlertDialogOverlay: any
  export const AlertDialogPortal: any
  export const AlertDialogTitle: any
  export const AlertDialogTrigger: any
  export const AlertTitle: any
  export const Button: any
  export const buttonVariants: any
  export const ButtonGroup: any
  export const ButtonGroupItem: any
  export const ButtonGroupSeparator: any
  export const ButtonGroupText: any
  export const buttonGroupVariants: any
  export const Calendar: any
  export const CalendarDayButton: any
  export const Card: any
  export const CardAction: any
  export const CardContent: any
  export const CardDescription: any
  export const CardFooter: any
  export const CardHeader: any
  export const CardTitle: any
  export const Carousel: any
  export const CarouselContent: any
  export const CarouselItem: any
  export const CarouselNext: any
  export const CarouselPrevious: any
  export type CarouselApi = any
  export const ChartContainer: any
  export const ChartLegend: any
  export const ChartLegendContent: any
  export const ChartStyle: any
  export const ChartTooltip: any
  export const ChartTooltipContent: any
  export const Checkbox: any
  export const ContextMenu: any
  export const ContextMenuCheckboxItem: any
  export const ContextMenuContent: any
  export const ContextMenuGroup: any
  export const ContextMenuItem: any
  export const ContextMenuLabel: any
  export const ContextMenuPortal: any
  export const ContextMenuRadioGroup: any
  export const ContextMenuRadioItem: any
  export const ContextMenuSeparator: any
  export const ContextMenuShortcut: any
  export const ContextMenuSub: any
  export const ContextMenuSubContent: any
  export const ContextMenuSubTrigger: any
  export const ContextMenuTrigger: any
  export const Field: any
  export const FieldContent: any
  export const FieldDescription: any
  export const FieldError: any
  export const FieldGroup: any
  export const FieldLabel: any
  export const FieldLegend: any
  export const FieldSeparator: any
  export const FieldSet: any
  export const FieldTitle: any
  export const Input: any
  export const InputGroup: any
  export const InputGroupAddon: any
  export const InputGroupButton: any
  export const InputGroupInput: any
  export const InputGroupText: any
  export const InputGroupTextarea: any
  export const Item: any
  export const ItemActions: any
  export const ItemContent: any
  export const ItemDescription: any
  export const ItemFooter: any
  export const ItemGroup: any
  export const ItemHeader: any
  export const ItemMedia: any
  export const ItemSeparator: any
  export const ItemTitle: any
  export const Kbd: any
  export const KbdGroup: any
  export const Label: any
  export const Menubar: any
  export const MenubarCheckboxItem: any
  export const MenubarContent: any
  export const MenubarGroup: any
  export const MenubarItem: any
  export const MenubarLabel: any
  export const MenubarMenu: any
  export const MenubarPortal: any
  export const MenubarRadioGroup: any
  export const MenubarRadioItem: any
  export const MenubarSeparator: any
  export const MenubarShortcut: any
  export const MenubarSub: any
  export const MenubarSubContent: any
  export const MenubarSubTrigger: any
  export const MenubarTrigger: any
  export const Pagination: any
  export const PaginationContent: any
  export const PaginationEllipsis: any
  export const PaginationItem: any
  export const PaginationLink: any
  export const PaginationNext: any
  export const PaginationPrevious: any
  export const Popover: any
  export const PopoverAnchor: any
  export const PopoverContent: any
  export const PopoverTrigger: any
  export const Progress: any
  export const RadioGroup: any
  export const RadioGroupItem: any
  export const Separator: any
  export const Sheet: any
  export const SheetClose: any
  export const SheetContent: any
  export const SheetDescription: any
  export const SheetFooter: any
  export const SheetHeader: any
  export const SheetTitle: any
  export const SheetTrigger: any
  export const Sidebar: any
  export const SidebarContent: any
  export const SidebarFooter: any
  export const SidebarGroup: any
  export const SidebarGroupAction: any
  export const SidebarGroupContent: any
  export const SidebarGroupLabel: any
  export const SidebarHeader: any
  export const SidebarInput: any
  export const SidebarInset: any
  export const SidebarMenu: any
  export const SidebarMenuAction: any
  export const SidebarMenuBadge: any
  export const SidebarMenuButton: any
  export const SidebarMenuItem: any
  export const SidebarMenuSkeleton: any
  export const SidebarMenuSub: any
  export const SidebarMenuSubButton: any
  export const SidebarMenuSubItem: any
  export const SidebarProvider: any
  export const SidebarRail: any
  export const SidebarSeparator: any
  export const SidebarTrigger: any
  export const Skeleton: any
  export const Spinner: any
  export const Switch: any
  export const Table: any
  export const TableBody: any
  export const TableCaption: any
  export const TableCell: any
  export const TableFooter: any
  export const TableHead: any
  export const TableHeader: any
  export const TableRow: any
  export const Tabs: any
  export const TabsContent: any
  export const TabsList: any
  export const TabsTrigger: any
  export const Textarea: any
  export const Toggle: any
  export const toggleVariants: any
  export const ToggleGroup: any
  export const ToggleGroupItem: any
  export const Tooltip: any
  export const TooltipContent: any
  export const TooltipProvider: any
  export const TooltipTrigger: any
  export const Toaster: any
  export const cn: (...args: any[]) => string
  export const useSidebar: any
}
